site_name: SNUAILAB Waffle
repo_url: https://github.com/snuailab/waffle_hub
repo_name: snuailab/waffle_hub

theme:
  name: material
  logo: assets/waffle_icon_gray.png
  favicon: assets/waffle_icon.png
  palette:
    primary: orange
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.footer
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/snuailab/waffle_hub

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/snuailab/mycompany/

    - icon: fontawesome/brands/medium
      link: https://medium.com/snuailab

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Documentations:
    - Waffle Utils:
      - Dataset:
        - Introduction: waffle_utils/dataset/index.md
        - Create Dataset: waffle_utils/dataset/dataset.md
        - Field: waffle_utils/dataset/field.md
      - Utility:
        - Introduction: waffle_utils/utility/index.md

    - Waffle Hub:
      - Hub:
        - Introduction: waffle_hub/hub/index.md
        - Create Hub: waffle_hub/hub/hub.md
        - Train: waffle_hub/hub/train.md
        - Inference: waffle_hub/hub/inference.md
        - Evaluate: waffle_hub/hub/evaluate.md
        - Export: waffle_hub/hub/export.md
      - Model:
        - Introduction: waffle_hub/model/index.md
        - Wrapper: waffle_hub/model/wrapper.md
  - Experimental:
    - Model Serve: experimental/model_serve.md
  - Blogs: None
