name: ðŸ› Bug Report
description: Problems with Project
labels: [bug, triage]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com///issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the [issues](https://github.com///issues) and found no similar bug report.
          required: true

  - type: dropdown
    attributes:
      label: Select Component
      description: |
        Please select the component where you found the bug.
      multiple: true
      options:
        - "apple"
        - "banana"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the software and hardware you used to produce the bug.
      placeholder: |
        - OS: Ubuntu version
        - Python: version
    validations:
      required: false

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem.
        This is referred to by community members as creating a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
